### ISSUE TITLE
Paths for photoswipe js files?

### ISSUE THREAD

**Issue by macsupport** [yaquawa/jquery.photoswipe#1]
Wondering why these 2 photoswipe paths (for OS X) are in your js file?

`{"/Applications/MAMP/htdocs/jquery.photoswipe/node_modules/photoswipe/dist/photoswipe-ui-default.js":1,"/Applications/MAMP/htdocs/jquery.photoswipe/node_modules/photoswipe/dist/photoswipe.js":2}`

**Comment by yaquawa** [comment]
@macsupport This is because the final js file is compiled by Browserify and Babelify. The original source code is located in `src/jquery.photoswipe.js`.
Anyway, this "path" really could be any string, it's just for identifying modules.
