### ISSUE TITLE
Bind Photoswipe to another trigger

### ISSUE THREAD

**Issue by ursbraem** [yaquawa/jquery.photoswipe#11]
Hi again!

In a project where I'm already using jquery.photoswipe for "regular" galleries (where you can click each thumbnail to open an image), I'd like to stick to your plugin for the following case also:

There's only a trigger button ("open gallery"). All the gallery's content is hidden. On click, the gallery launches. 

Should I use jquery.photoswipe for that at all? If so, (how) would that work?

Or should I rather try to use the vanilla photoswipe directly? Can those two (vanilla pswp and your plugin) run alongside on the same page?

**Comment by ursbraem** [comment]
Here's my current quick & dirty solution...

```
$('#launch-gallery').on('click', function (e) {
  event.preventDefault();
  window.location.href += "#&gid=1&pid=1";
  location.reload();
});
```

... seen prettier things!

**Comment by ursbraem** [comment]
Unfortunately, my above ugly solution doesn't work with multiple galleries on a page (if you don't know which gallery it will be), as &gid changes

**Comment by yaquawa** [comment]
Hi ursbraem.

Try if this works.

```js
$('#launch-gallery').on('click', function (e) {
	e.preventDefault();
	$('#hidden-gallery .thumbnail').eq(0).trigger('click');
});
```

**Comment by ursbraem** [comment]
Wohooo! Yes it does.
I wrote the counter hard into the html, so this also worked:
```
$('#launch-gallery').on('click', function (e) {
	e.preventDefault();
	$('#hidden-gallery .thumbnail-0').trigger('click');
});
```

Thanks a lot!!!! So good.
