### ISSUE TITLE
photoswipe loads data-original-src with thumbnail dimensions

### ISSUE THREAD

**Issue by magicdarvin** [yaquawa/jquery.photoswipe#2]
Hello, 

I'm using the markup where I have data-original-src but without data-original-src-width or data-original-src-height specified, like in this example:
`<div id="gallery">
<img src="images/thumb/IMG_2969.jpg" data-original-src="images/full/IMG_2969.jpg">
</div>`

The problem is that when I click on the thumbnail PhotoSwipe opens the data-original-src image with the same width and height as the thumbnail. So basically it loads the big image but with the dimensions of the thumbnail, without any further possibility to zoom it in or out. 
**Is it somehow possible to get the data-original-src image opened with its original dimensions?**

Here is how it works for me now: 
http://magicdarvin.github.io/issue.html
The thumbnails width is about 300, the data-original-src images width is about 2000. 

There is also a line in the Readme, which made me think that actually this should have worked just out of the box:

> ```
> If the `data-original-src-width` or `data-original-src-width` not exists, the natural width and height of this image will be used. 
> ```

Though, maybe it is just my misinterpretation of what is _natural width and height of this image_. 

Thank you.

**Comment by yaquawa** [comment]
I apologise for any confusion caused...

The answer is that because you specified the `data-original-src`. 
If you'd like to let the plugin figure out the width and height of the original image, you had to set the 'src' to the original image, and remove the `data-original-src`.

**Comment by magicdarvin** [comment]
Thank you for such a quick reply and for sure no apology necessary. 

With the scenario you've described everything works as expected - photoswipe opens the image with its original dimensions. 

The only thing is that there is not always such an opportunity to use original images for a gallery. Even though it is possible to scale the images through css and use them as thumbnails, still if there are a lot of images on a page or a lot of galleries with a bunch of images in each, the browser would have to load all of this original images from the page and here when it becomes an issue, especially for mobile devices. 
This is the reason for a lot of people to use the technique with two (some times more) images - a thumbnail image and an original image. **And this is why I'm so willing to figure out whether it is somehow possible to get the `data-original-src` image opened with its original dimensions. It might be considered as a feature request for the plugin.**

Meanwhile, I found a workaround, which i think is far from being a proper one, but anyways, I have modified `jquery.photoswipe-global.js`, the part `function getWH(wh, $img) {`, particularly                 `d.resolve(this[wh]);` , I have added `*5`. 
So in the end it looks like this `d.resolve(this[wh]*5);`.
Because I know that the thumbnails I generate are around 5 times smaller than the original images this multiple by 5 does the trick. You can check how it works here http://magicdarvin.github.io/issue .
For now it seems working fine both on desktop and mobile. 

Thank you.

**Comment by yaquawa** [comment]
What you say is quite right, but the problem is that PhotoSwipe requires ALL the size information(width and height) of the images before you can initialize it. I'm not sure why PhotoSwipe has such a limitation, hopefully the future version of PhotoSwipe will get a more elegant solution, for the meantime I don't think there is a perfect workaround😅 I have to say the workaround you just showed me maybe the best one for now.

**Comment by magicdarvin** [comment]
yeah, i know about this dimensions requirement. The author partly addresses this issue here http://photoswipe.com/documentation/faq.html#image-size and also in regard to his other plugin magnificent loop here https://www.smashingmagazine.com/2013/05/truly-responsive-lightbox/#touch-swipe-support . I just thought there is a way to get the dimensions of the `data-original-src` using jquery. But the thing is that I don't know javascript at all and without your plugin I'm not sure if i even could get photoswipe running on my webpage at all . So I'm very grateful for the plugin. It really helped me a lot!

**Comment by yaquawa** [comment]
Thank you!

I just did a little adjustment of the code.
Now the plugin takes dimension information from the image file name.

e.g. images/IMG_3012-1200x800.jpg

So if the filename include the dimension information you don't need to specify `data-original-src-width` and `data-original-src-width` now.

I know you still have to rename the filenames... but I think this is the best way as far as I know.

**Comment by magicdarvin** [comment]
It is a great solution for those who are using batch image converting software to process images. Then it's pretty easy to change the images file names while generating thumbnails. Which I'm actually doing, so maybe I'll switch to this solution as a more proper one. Thanks!
