### ISSUE TITLE
bower.io

### ISSUE THREAD

**Issue by VladimirIvanin** [yaquawa/jquery.photoswipe#3]
The plugin will be added in bower?

**Comment by kaisermann** [comment]
+1. Would be interesting for assets workflows that automatically uses bower

**Comment by yaquawa** [comment]
Unfortunately, I don't plan to add it to the bower.

As of npm3, flat dependency tree was supported (just like bower), there is no benefit for a front-end developer to use Bower over npm now.

This post may be helpful.
[What is the difference between Bower and npm?](http://stackoverflow.com/questions/18641899/what-is-the-difference-between-bower-and-npm)

**Comment by johandelforge** [comment]
Hello Yaquawa, 

i'm also missing the bower package :).   I understand your point, but it's a real pain to have front-end dependencies sitting in a very large node_modules folder....  I'm not lying when jquery.photoswipe is the only extension i use that is not on bower.

Best regards...
