### ISSUE TITLE
Get caption from elsewhere than alt-text

### ISSUE THREAD

**Issue by ursbraem** [yaquawa/jquery.photoswipe#4]
Hi and thank you so much for this! I would have found it too difficult to start with photoswipe without your plugin.

I was wondering: jquery.photoswipe seems to pick the caption from the alt text.
https://github.com/yaquawa/jquery.photoswipe/blob/master/dist/jquery.photoswipe-global.js#L4452

 I want it to pick it from somewhere else, like a data-attribute. Can I override that somehow or would I have to fork the plugin for that and edit it directly in the code?

**Comment by yaquawa** [comment]
@ursbraem

Yes, it'll use the `alt` attribute as the caption text, which I think it's the easiest way to keep the markup semantic. 

As you could find in the source code, it's very easy to add additional references to use, like data attribute, etc.

What do you exactly want the 'somewhere' to be? I'd like to add the 'somewhere' for you :)

**Comment by ursbraem** [comment]
>  I'd like to add the 'somewhere' for you

Oh, thanks! That's very kind!

>  it'll use the alt attribute as the caption text, which I think it's the easiest way to keep the markup semantic.

It's actually not correct from a semantic point of view. An example:
- Photo of a steel worker
- Alt Text for visually impaired, SEO etc.(describes the photo content): Steel worker in factory 
- Caption (mostly `<figcaption>`) in addition to the photo: Steel factories are hot places! 

-> a seeing person will see the photo of a steel worker, accompanied by the sassy caption
-> a screenreader will read the alt text AND the sassy caption

cf. https://en.wikipedia.org/wiki/Alt_attribute

> What do you exactly want the 'somewhere' to be? 

`<img src="images/IMG_2969--thumbnail.jpg" data-original-src="images/IMG_2969.jpg" data-original-src-width="2000" data-original-src-height="2000" data-caption="caption text" alt="alt text">`

In the markup, data-caption would be a duplicate of the real `<figcaption>` further down the markup. 

If you'd do that (or should I make a pull request?), to avoid it being a breaking change, you could make a condition that checks for the data-caption and falls back to `alt` if `data-caption` is not present. 

PS:  I have some more questions, is it ok if I bother you here with them? And, do you accept donations? Or maybe we could even hire you for a small amount of time to do some customisations?

**Comment by yaquawa** [comment]
> It's actually not correct from a semantic point of view

Oh, that's good to know! Thanks for the example.

> In the markup, data-caption would be a duplicate of the real <figcaption> further down the markup.

Then how about using a `data-caption-id` that points to the real `<figcaption>` by it's `id` attribute? Just like the way how `list` attribute works in `<input/>` element.

> PS: PS: I have some more questions, is it ok if I bother you here with them? And, do you accept donations? Or maybe we could even hire you for a small amount of time to do some customisations?

Sure, keep asking. And thank you for your concern. It's a piece of cake for me, don't hesitate to ask :)

**Comment by ursbraem** [comment]
> Then how about using a data-caption-id that points to the real <figcaption> by it's id attribute? Just like the way how list attribute works in <input/> element.

Yes, why not – less bloat. but it would have to be a class, not an id, as there are several captions on the page. So 

```
<figure class="item">
<img>
<figcaption class="caption"></figcaption>
</figure>
```

but also this would work:

```
<div class="item">
<img>
<div class="caption"></div>
</div>
```

**Comment by ursbraem** [comment]
> It's a piece of cake for me, don't hesitate to ask
> good to know, thanks!

**Comment by yaquawa** [comment]
@ursbraem
I've updated the source and the readme doc.
https://github.com/yaquawa/jquery.photoswipe/blob/master/src/jquery.photoswipe.js#L92-L127

Now you can take the caption text from the `figcaption` element. And you don't need to specify a `data-caption` if you have a `figcaption` element inside a `figure` element which contains your `img`.

**Comment by ursbraem** [comment]
Wonderful, and great with the auto-descovery of figcaption as well as the other options – thanks!!!
