### ISSUE TITLE
Multiple blocks of images, one photoswipe

### ISSUE THREAD

**Issue by ursbraem** [yaquawa/jquery.photoswipe#5]
My page has this structure

* a block of images (actually an owl.carousel)
* some text
* another block of images
* some text
* maybe a single image 
* etc

I've added the class "photoswipe" to the wrapper each image block and triggered it with `    $('.photoswipe').photoSwipe();`

Now this seems to make multiple instances of photoswipe galleries, one for each block.
What I want is one photoswipe gallery over all concerned images of the page. 

In older lightboxes, this would be done with a rel="" attribute, assigning a group to each image.
How would this be done with photoswipe?

**Comment by yaquawa** [comment]
Try this.

`$('.galleries-container').photoSwipe('.slide');`

The `.galleries-container` is the container that contains all of your slides(images).
The `.slide` indicates those elements that contain your `img` element. If you leave it blank the default value 'img' will be used.

**Comment by ursbraem** [comment]
yes!! thanks!!
